# Generated by Django 5.0.4 on 2024-05-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
