# Generated by Django 5.0.4 on 2024-05-10 14:00

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='talentprofile',
            name='cv_document',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='file'),
        ),
        migrations.AddField(
            model_name='talentprofile',
            name='services',
            field=models.ManyToManyField(related_name='talent_profiles', to='src.service'),
        ),
        migrations.AddField(
            model_name='talentprofile',
            name='work_experiences',
            field=models.TextField(blank=True, null=True),
        ),
    ]
