# Generated by Django 5.0.4 on 2024-05-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_talentprofile_cv_document_talentprofile_services_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='talentprofile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
