# Generated by Django 5.0.4 on 2024-05-09 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('category', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('hiring_company', models.CharField(max_length=200)),
                ('tag', models.CharField(choices=[('Remote', 'Remote'), ('Onsite', 'Onsite'), ('Hybrid', 'Hybrid'), ('Full-time', 'Full-time'), ('Part-time', 'Part-time')], max_length=20)),
                ('requirements', models.TextField()),
            ],
        ),
    ]
