# Generated by Django 5.0.4 on 2024-05-09 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job', '0001_initial'),
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='talent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.talentprofile'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='job_opportunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.jobopportunity'),
        ),
    ]
