# Generated by Django 5.0.4 on 2024-05-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopportunity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
